name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  analyze-sandbox:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4

      - uses: Roblox/setup-foreman@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          allow-external-github-orgs: true

      - name: Run just luau-lsp, no arguments
        shell: bash
        run: luau-lsp
