name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  analyze-sandbox:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, ubuntu-22.04, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4

      - uses: Roblox/setup-foreman@v3.2.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: v1.6.0
          allow-external-github-orgs: true

      - name: Log Foreman info
        run: |
          foreman --version
          foreman list

      - name: Run just luau-lsp, no arguments
        shell: bash
        run: luau-lsp --help
