name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  analyze-sandbox:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4

      - name: Setup Foreman manually
        run: |
          curl -LO https://github.com/Roblox/foreman/releases/download/v1.6.4/foreman-linux-x86_64.zip
          unzip foreman-linux-x86_64.zip
          chmod +x ./foreman
          ./foreman install --verbose

      - name: Log Foreman info
        run: |
          ./foreman --version
          ./foreman list

      - name: Run just luau-lsp, no arguments
        shell: bash
        run: luau-lsp --help

  other-platforms:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4

      - uses: Roblox/setup-foreman@v3.2.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          allow-external-github-orgs: true

      - name: Log Foreman info
        run: |
          foreman --version
          foreman list

      - name: Run just luau-lsp, no arguments
        shell: bash
        run: luau-lsp --help
